Controllers/SolicitudHorasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;

using System.Web.Mvc;
using SistemaHE.Models;

namespace SistemaHE.Controllers
{
    public class SolicitudHorasController : Controller
    {
        private SitiosWebEntities db = new SitiosWebEntities();
        public busqueda b = new busqueda();
        
        // GET: SolicitudHoras
        public ActionResult Index()
        {
            int cedula = Convert.ToInt32(Session["Cedula"]);
            if (Session["Rol"].Equals("Jefe"))
            {
                var soli = from d in db.SolicitudHoras
                           where d.JefeDestinatario == cedula || d.Remitente==cedula && d.Estado !="Rechazado"
                           select d;
             
                return View(soli.ToList());
            }
            else
            {
                var soli = from d in db.SolicitudHoras
                           where d.Remitente == cedula || d.Destinatario1==cedula || d.Destinatario2 == cedula || d.Destinatario3 == cedula && d.Estado != "Rechazado"
                           select d;
             

                return View(soli.ToList());
            }



        }


        // GET: SolicitudHoras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SolicitudHoras solicitudHoras = db.SolicitudHoras.Find(id);
            if (solicitudHoras == null)
            {
                return HttpNotFound();
            }
            return View(solicitudHoras);
        }







        // GET: SolicitudHoras/Create
        public ActionResult Create()
        {
            
            var destinatarios = from d in db.Usuarios
                        where d.Rol == "Funcionario"
                        select d;

         

            ViewBag.Destinatario1 = new SelectList(destinatarios, "Identificacion", "Nombre_Completo");
            ViewBag.Destinatario2 = new SelectList(destinatarios, "Identificacion", "Nombre_Completo");
            ViewBag.Destinatario3 = new SelectList(destinatarios, "Identificacion", "Nombre_Completo");
            ViewBag.ID_Tarea = new SelectList(db.Tareas, "ID_Tarea", "DetalleDeLaTarea");
         
            
            return View();
        }

        // POST: SolicitudHoras/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Transaccion,CantidadDeHoras,ID_Tarea,Remitente,JefeDestinatario,Destinatario1,Destinatario2,Destinatario3,Estado")] SolicitudHoras solicitudHoras)
        {
            if (ModelState.IsValid)
            {

                if (Session["Rol"].Equals("Jefe"))
                {
                    solicitudHoras.JefeDestinatario = null;


                }
                else
                {
                    solicitudHoras.JefeDestinatario = Convert.ToInt32(Session["CedulaJefe"]);
                    solicitudHoras.Destinatario1 = null;
                    solicitudHoras.Destinatario2 = null;
                    solicitudHoras.Destinatario3 = null;
                }
                solicitudHoras.Remitente = Convert.ToInt32(Session["Cedula"]);
                solicitudHoras.Estado = "Pendiente";

                db.SolicitudHoras.Add(solicitudHoras);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var destinatarios = from d in db.Usuarios
                                where d.Rol == "Funcionario"
                                select d;
            ViewBag.Destinatario1 = new SelectList(destinatarios, "Identificacion", "Nombre_Completo", solicitudHoras.Destinatario1);
            ViewBag.Destinatario2 = new SelectList(destinatarios, "Identificacion", "Nombre_Completo", solicitudHoras.Destinatario2);
            ViewBag.Destinatario3 = new SelectList(destinatarios, "Identificacion", "Nombre_Completo", solicitudHoras.Destinatario3);
            ViewBag.ID_Tarea = new SelectList(db.Tareas, "ID_Tarea", "DetalleDeLaTarea", solicitudHoras.ID_Tarea);
            var jefes = db.ListaJefes().ToList();
            ViewBag.JefeDestinatario = new SelectList(jefes, "Identificacion", "Nombre_Completo", solicitudHoras.JefeDestinatario);
            ViewBag.Remitente = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", solicitudHoras.Remitente);
            return View(solicitudHoras);
        }

        // GET: SolicitudHoras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SolicitudHoras solicitudHoras = db.SolicitudHoras.Find(id);
            Session["ID_Soli"] = id;
            if (solicitudHoras == null)
            {
                return HttpNotFound();
            }
            List<string> listOfNames = new List<string>() { "Pendiente", "Aceptado", "Rechazado" };
            ViewBag.Estado = new SelectList(listOfNames,solicitudHoras.Estado);
            ViewBag.CantidadDeHoras = solicitudHoras.CantidadDeHoras;

            ViewBag.Destinatario1 =b.buscarNom(Convert.ToInt32( solicitudHoras.Destinatario1));
            ViewBag.Destinatario2 = b.buscarNom(Convert.ToInt32(solicitudHoras.Destinatario2));
            ViewBag.Destinatario3 = b.buscarNom(Convert.ToInt32(solicitudHoras.Destinatario3));
            ViewBag.ID_Tarea = b.buscarTar(Convert.ToInt32(solicitudHoras.ID_Tarea));
            ViewBag.JefeDestinatario = b.buscarNom(Convert.ToInt32(solicitudHoras.JefeDestinatario));
            ViewBag.Remitente = b.buscarNom(Convert.ToInt32(solicitudHoras.Remitente));

            return View(solicitudHoras);
        }

    

        // POST: SolicitudHoras/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                SolicitudHoras solicitudHoras = db.SolicitudHoras.Find(Convert.ToInt32(Session["ID_Soli"]));
               
                solicitudHoras.Estado = Request["Estado"].ToString();


                string mensaje = Session["Nombre"] + " ha " + solicitudHoras.Estado.ToString() + " la solicitud: N° " + solicitudHoras.ID_Transaccion + ", correspondiente a la tarea: " + solicitudHoras.Tareas.DetalleDeLaTarea+"\n"+"Comentario:\n"+Request["Comentario"];

          
                    var correo = from d in db.Usuarios
                                 where d.Identificacion == solicitudHoras.Remitente
                                 select d;
                    foreach (var item in correo)
                    {
                        Correos correos = new Correos(item.Correo, item.Nombre_Completo, "Cambios en Solicitud de Horas Extras", mensaje);
    
                

                }

                db.Entry(solicitudHoras).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            SolicitudHoras solicitudHoras2 = db.SolicitudHoras.Find(Convert.ToInt32(Session["ID_Soli"]));

            ViewBag.Destinatario1 = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", solicitudHoras2.Destinatario1);
            ViewBag.Destinatario2 = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", solicitudHoras2.Destinatario2);
            ViewBag.Destinatario3 = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", solicitudHoras2.Destinatario3);
            ViewBag.ID_Tarea = new SelectList(db.Tareas, "ID_Tarea", "DetalleDeLaTarea", solicitudHoras2.ID_Tarea);
            ViewBag.JefeDestinatario = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", solicitudHoras2.JefeDestinatario);
            ViewBag.Remitente = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", solicitudHoras2.Remitente);
            return View(solicitudHoras2);
        }

        // GET: SolicitudHoras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SolicitudHoras solicitudHoras = db.SolicitudHoras.Find(id);
            if (solicitudHoras == null)
            {
                return HttpNotFound();
            }
            return View(solicitudHoras);
        }

        // POST: SolicitudHoras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SolicitudHoras solicitudHoras = db.SolicitudHoras.Find(id);
            db.SolicitudHoras.Remove(solicitudHoras);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout _ Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link href="~/Content/Principal.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>

    <nav id="H1">

    </nav>

    <div id="H2">
        <nav class="white">
            <div class="nav-wrapper white">

                <a href="#" class="logo"><img src="~/image/1.png" alt="Dimario" /></a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                </ul>

                <div id="data">
                    <h2>
                        @Session["Nombre"]
                        @Session["Cedula"]
                        <br>
                        @Session["Rol"]
                    </h2>

                    <h2></h2>
                </div>
            </div>
        </nav>
    </div>

    <div id="H3">

        <div id="Hed">

            <div class="topnav" id="myTopnav">
                <div id="anchoN">
                    <a href="#home" class="active">@Html.ActionLink("Inicio", "Index", "Home", new object { }, new { @class = "blue-text text-darken-2" })</a>

                    @Html.ActionLink("Cerrar Sesion", "Login", "Home")
                    @Html.ActionLink("Acerca de", "About", "Home")
                    @Html.ActionLink("Usuarios", "Index", "Usuarios")

                    @Html.ActionLink("Departamentos", "Index", "Departamentos")

                    @Html.ActionLink("Cuentas", "Index", "Cuentas")






                </div>

                <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
            </div>





        </div>


    </div>


    <div class="container">
        @RenderBody()
    </div>




    <div class="page-footer">

        <p>&copy; @DateTime.Now.Year - DIMARIO</p>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @Scripts.Render("~/bundles/init")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout _ Director.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link href="~/Content/Principal.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>

    <nav id="H1">

    </nav>

    <div id="H2">
        <nav class="white">
            <div class="nav-wrapper white">

                <a href="#" class="logo"><img src="~/image/1.png" alt="Dimario" /></a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                </ul>
                <div id="data">
                    <h2>
                        @Session["Nombre"]
                        @Session["Cedula"]
                        <br>
                        @Session["Rol"]
                    </h2>

                    <h2></h2>
                </div>
            </div>
        </nav>
    </div>



    @*<li>
        @Html.ActionLink("Inicio", "Index", "Home", new object { },
new { @class = "blue-text text-darken-2" })
    </li>
    <li>@Html.ActionLink("Cerrar Sesion", "Login", "Home")</li>
    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
    <li>@Html.ActionLink("Tareas", "Index", "Tareas")</li>*@


<div id="H3">

    <div id="Hed">

        <div class="topnav" id="myTopnav">
            <div id="anchoN">
                <a href="#home" class="active">@Html.ActionLink("Inicio", "Index", "Home", new object { }, new { @class = "blue-text text-darken-2" })</a>

                @Html.ActionLink("Cerrar Sesion", "Login", "Home")
                @Html.ActionLink("Acerca de", "About", "Home")
                @Html.ActionLink("Tareas", "Index", "Tareas")

                @Html.ActionLink("Cuenta", "Index", "Cuentas")

            </div>

            <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
        </div>





    </div>


</div>


    <div class="container">
        @RenderBody()
    </div>




    <div class="page-footer">

        <p>&copy; @DateTime.Now.Year - DIMARIO</p>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @Scripts.Render("~/bundles/init")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout _ Funcionario.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>

    <nav id="H1">

    </nav>

    <div id="H2">
        <nav class="white  ">
            <div class="nav-wrapper white">

                <a href="#" class="logo"><img src="~/image/1.png" alt="Dimario" /></a>
                @*<a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                    </ul>*@
                <div id="data">
                    <h2>
                        @Session["Nombre"]
                        @Session["Cedula"]
                        <br>
                        @Session["Rol"]
                    </h2>

                    <h2></h2>
                </div>
            </div>

        </nav>
    </div>

    @*<li>@Html.ActionLink("Horas Extra", "Create", "SolicitudHoras", new object { }, new { @class = "blue-grey darken-3" })</li>
    <li>@Html.ActionLink("Personal Extra", "SolicitudPE", "SolicitudHoras", new object { }, new { @class = "blue-grey darken-3" })</li>*@


<div id="H3">

    <div id="Hed">

        <div class="topnav" id="myTopnav">
            <div id="anchoN">
                <a href="#home" class="active">@Html.ActionLink("Inicio", "Index", "Home", new object { }, new { @class = "green-text text-darken-2" })</a>
                <a href="@Url.Action("Login", "Home")" class="">
                    <span>
                        <strong>Cerrar Sesion</strong>
                    </span>
                </a>
                <a href="@Url.Action("About", "Home")" class="">
                    <span>
                        <strong>Acerca de</strong>
                    </span>
                </a>
                <a class='dropdown-trigger  transparent ' href='#' data-target='dropdown1'>Solicitudes</a>

                <ul id='dropdown1' class='dropdown-content black-text '>

                    <li>@Html.ActionLink("Horas Extra", "Index", "SolicitudHoras", new object { }, new { @class = "" })</li>

                    <li>@Html.ActionLink("Personal Extra", "Index", "SolicitudPersonals", new object { }, new { @class = "" })</li>




                </ul>


                @Html.ActionLink("Cuenta", "Index", "Cuentas")


            <a href="~/Views/Reportes/Index.cshtml">Reportes Diarios</a>

            </div>

            <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
        </div>





    </div>


</div>


    <div class="container">
        @RenderBody()
    </div>




    <div class="page-footer">

        <p>&copy; @DateTime.Now.Year - DIMARIO</p>

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @Scripts.Render("~/bundles/init")
    @Scripts.Render("~/bundles/init")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout _ Jefe.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")

</head>
<body>

    <nav id="H1">

    </nav>

    <div id="H2">
        <nav class="white  ">
            <div class="nav-wrapper white">

                <a href="#" class="logo"><img src="~/image/1.png" alt="Dimario" /></a>

                <div id="data">
                    <h2>
                        @Session["Nombre"]
                        @Session["Cedula"]
                        <br>
                        @Session["Rol"]
                    </h2>

                    <h2></h2>
                </div>

            </div>


        </nav>



    </div>




    <div id="H3">

        <div id="Hed">

            <div class="topnav" id="myTopnav">
                <div id="anchoN">
                    <a href="#home" class="active">@Html.ActionLink("Inicio", "Index", "Home", new object { }, new { @class = "green-text text-darken-2" })</a>
                    <a href="@Url.Action("Login", "Home")" class="">
                        <span>
                            <strong>Cerrar Sesion</strong>
                        </span>
                    </a>
                    <a href="@Url.Action("About", "Home")" class="">
                        <span>
                            <strong>Acerca de</strong>
                        </span>
                    </a>
                    <a class='dropdown-trigger  transparent ' href='#' data-target='dropdown1'>Servicios</a>

                    <ul id='dropdown1' class='dropdown-content black-text '>

                        <li>@Html.ActionLink("Horas Extra", "Index", "SolicitudHoras", new object { }, new { @class = "" })</li>

                        <li>@Html.ActionLink("Personal Extra", "Index", "SolicitudPersonals", new object { }, new { @class = "" })</li>




                    </ul>


                    @Html.ActionLink("Cuenta", "Index", "Cuentas")

                </div>

                <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
            </div>





        </div>


    </div>

    <div class="container">
        @RenderBody()
    </div>




    <div class="page-footer">

        <p>&copy; @DateTime.Now.Year - DIMARIO</p>

    </div>
    <script>





    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @Scripts.Render("~/bundles/init")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link href="~/Content/Principal.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>

    <nav id="H1">
      
    </nav>

    <div id="H2">
        <nav class=" white">
            <div class="nav-wrapper white">

                <a href="#" class="logo"><img src="~/image/1.png" alt="Dimario" /></a>
                
                <ul class="right hide-on-med-and-down">
                </ul>
            </div>
        </nav class="nav-wrapper>
    </div>

    <div id="H3">
    

    </div>

    <div class="container">
        @RenderBody()
    </div>


    <div class="page-footer ">
       
            <p>&copy; @DateTime.Now.Year - DIMARIO</p>
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout_login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Cuentas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>