Models/Departamento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public int ID_Departamento { get; set; }
        public int Identificacion { get; set; }
        public string Nombre_Departamento { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}

Models/Departamentos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public int ID_Departamento { get; set; }
        public string Nombre_Departamento { get; set; }
    }
}

Controllers/DepartamentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaHE.Models;

namespace SistemaHE.Controllers
{
    public class DepartamentosController : Controller
    {
        private SitiosWebEntities db = new SitiosWebEntities();

        // GET: Departamentos
        public ActionResult Index()
        {
            return View(db.Departamentos.ToList());
        }

        // GET: Departamentos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Departamentos departamentos = db.Departamentos.Find(id);
            if (departamentos == null)
            {
                return HttpNotFound();
            }
            return View(departamentos);
        }

        // GET: Departamentos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departamentos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Departamento,Nombre_Departamento")] Departamentos departamentos)
        {
            if (ModelState.IsValid)
            {
                db.Departamentos.Add(departamentos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(departamentos);
        }

        // GET: Departamentos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Departamentos departamentos = db.Departamentos.Find(id);
            if (departamentos == null)
            {
                return HttpNotFound();
            }
            return View(departamentos);
        }

        // POST: Departamentos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Departamento,Nombre_Departamento")] Departamentos departamentos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(departamentos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(departamentos);
        }

        // GET: Departamentos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Departamentos departamentos = db.Departamentos.Find(id);
            if (departamentos == null)
            {
                return HttpNotFound();
            }
            return View(departamentos);
        }

        // POST: Departamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Departamentos departamentos = db.Departamentos.Find(id);
            db.Departamentos.Remove(departamentos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Departamentos/Create.cshtml
@model SistemaHE.Models.Departamentos

@{
    ViewBag.Title = "Create";
}
<div id="textoH">
    <br />
    <h2>Departamentos</h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div id="ContentL">
        <div class="ContenidoL">

            <div class="form-horizontal">
                <h4>Agregar</h4>
                
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div id="formula">
                    <div class="row">
                        <div class="col l6">
                            @Html.LabelFor(model => model.ID_Departamento,"ID Departamento", htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.EditorFor(model => model.ID_Departamento, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ID_Departamento, "", new { @class = "text-danger" })
                        </div>



                        <div class="col l6">
                            @Html.LabelFor(model => model.Nombre_Departamento, "Nombre Departamento", htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.EditorFor(model => model.Nombre_Departamento, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre_Departamento, "", new { @class = "text-danger" })
                        </div>

                    </div>

                </div>
                <div id="pagina">

                    <input type="submit" value="Agregar" class="waves-button-input btn-small" />


                    @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small" })

                </div>
            </div>
        </div>
    </div>


}

Views/Departamentos/Delete.cshtml
@model SistemaHE.Models.Departamentos

@{
    ViewBag.Title = "Delete";
}
<div id="textoH">
    <br />
    <h2>Departamentos</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



    <div id="ContentL">

        <div class="ContenidoL">
            <h3>¿Está seguro que desea eliminar esto?</h3>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Nombre_Departamento)
            <div class="row">
                <div id="formula" class="col s6">
                    @Html.LabelFor(model => model.Nombre_Departamento, "Departamento")

                    @Html.EditorFor(model => model.Nombre_Departamento, new { htmlAttributes = new { disabled = "disabled" } })


                    



                </div>
            </div>
            <div id="pagina">
                @Html.ActionLink("Eliminar", "Edit", new { id = Model.Nombre_Departamento }, htmlAttributes: new { @class = "waves-button-input btn-small" })
                @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small " })
            </div>
        </div>
    </div>

}

Views/Departamentos/Details.cshtml
@model SistemaHE.Models.Departamentos

@{
    ViewBag.Title = "Details";
}
<div id="textoH">
    <br />
    <h2>Departamentos</h2>
</div>




<div id="ContentL">
    <div class="ContenidoL">
        <h3>Detalles</h3>
       
        <div class="row">
            <div id="formula" class="col s6">
                @Html.LabelFor(model => model.Nombre_Departamento, "Departamento")

                @Html.EditorFor(model => model.Nombre_Departamento, new { htmlAttributes = new { @class = "", disabled = "disabled" } })

            </div>

        </div>
        <div id="pagina">
            @Html.ActionLink("Editar", "Edit", new { id = Model.ID_Departamento }, htmlAttributes: new { @class = "waves-button-input btn-small " })
            @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small " })
        </div>
    </div>
</div>

Views/Departamentos/Edit.cshtml
@model SistemaHE.Models.Departamentos

@{
    ViewBag.Title = "Edit";
}

<div id="textoH">
    <br />
    <h2>Departamentos</h2>
</div>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div id="ContentL">

        <div class="ContenidoL">

            <h3>Editar</h3>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID_Departamento)

            <div class="row">
                <div id="formula" class="col s6">
                    @Html.LabelFor(model => model.Nombre_Departamento,"Nombre Departamento", htmlAttributes: new { @class = "control-label col-md-2" })


                    @Html.EditorFor(model => model.Nombre_Departamento, new { htmlAttributes = new { @class = "" } })
                    @Html.ValidationMessageFor(model => model.Nombre_Departamento, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="pagina">

                <input type="submit" value="Guardar" class="waves-button-input btn-small" />


                @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small" })

            </div>

        </div>
    </div>


}

Views/Departamentos/Index.cshtml
@model IEnumerable<SistemaHE.Models.Departamentos>

@{
    ViewBag.Title = "Index";
}
<div id="textoH">
    <br />
    <h2>Departamentos</h2>
</div>



<div id="ContentD">

    <div class="ContenidoD">


        <table class="table">
            <tr>
                <th>
                    Departamento
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre_Departamento, "Departamento")
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Departamentos", new { id = item.ID_Departamento })">
                            <i class="material-icons">edit</i>

                        </a>
                        <a href="@Url.Action("Details", "Departamentos", new { id = item.ID_Departamento })">
                            <i class="material-icons">search</i>

                        </a>
                        <a href="@Url.Action("Delete", "Departamentos", new { id = item.ID_Departamento })">
                            <i class="material-icons">delete</i>

                        </a>

                    </td>
                </tr>
            }

        </table>
        <div id="pagina">


            @Html.ActionLink("Agregar", "Create", null, htmlAttributes: new { @class = "waves-button-input btn-large " })

        </div>

    </div>
</div>