Models/Cuentas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int ID_Cuenta { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public string Contrasenna { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}

Controllers/CuentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaHE.Models;

namespace SistemaHE.Controllers
{
    public class CuentasController : Controller
    {
        private SitiosWebEntities db = new SitiosWebEntities();

        // GET: Cuentas
        public ActionResult Index()
        {

            //var cuentas = db.Cuentas.Include(c => c.Usuarios);

            int id = Convert.ToInt32(Session["Cedula"]);
            var cuentas = from d in db.Cuentas
                          where d.Identificacion == id
                          select d;
            
            return View(cuentas);
        }

        // GET: Cuentas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Cuentas cuentas = db.Cuentas.Find(id);
        
            if (cuentas == null)
            {
                return HttpNotFound();
            }
            return View(cuentas);
        }

        // GET: Cuentas/Create
        public ActionResult Create()
        {
            ViewBag.Identificacion = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo");
            return View();
        }

        // POST: Cuentas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Cuenta,Identificacion,Contrasenna")] Cuentas cuentas)
        {
            if (ModelState.IsValid)
            {
                Encriptado encriptado = new Encriptado();
                cuentas.Contrasenna = encriptado.Encrypt(cuentas.Contrasenna);
                db.Cuentas.Add(cuentas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Identificacion = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", cuentas.Identificacion);
            return View(cuentas);
        }

        // GET: Cuentas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cuentas cuentas = db.Cuentas.Find(id);
            cuentas.Contrasenna = "";
            if (cuentas == null)
            {
                return HttpNotFound();
            }
            ViewBag.Identificacion = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", cuentas.Identificacion);
            return View(cuentas);
        }

        // POST: Cuentas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Cuenta,Identificacion,Contrasenna")] Cuentas cuentas)
        {
            if (ModelState.IsValid)
            {
                if (cuentas.Identificacion!=707770777)
                {
                    Encriptado encriptado = new Encriptado();
                    cuentas.Contrasenna = encriptado.Encrypt(cuentas.Contrasenna);
                    cuentas.Identificacion = Convert.ToInt32(Session["Cedula"]);
                }
              
                db.Entry(cuentas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Identificacion = new SelectList(db.Usuarios, "Identificacion", "Nombre_Completo", cuentas.Identificacion);
            return View(cuentas);
        }

        // GET: Cuentas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cuentas cuentas = db.Cuentas.Find(id);
            if (cuentas == null)
            {
                return HttpNotFound();
            }
            return View(cuentas);
        }

        // POST: Cuentas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cuentas cuentas = db.Cuentas.Find(id);
            db.Cuentas.Remove(cuentas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Cuentas/Create.cshtml
@model SistemaHE.Models.SolicitudHoras


@{
    ViewBag.Title = "SolicitudHE";
}



<div id="textoH">
    <br />
    <h2>Solicitud Horas Extra</h2>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="ContentL">
        <div class="ContenidoL">
            <h3>Nueva Solicitud</h3>

            <div id="formula">
                <div class="row">
                    <div class="col l6">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        

                        @Html.DropDownList("ID_Tarea", null, htmlAttributes: new { @class = "dropdown-trigger btn" })
                        @Html.ValidationMessageFor(model => model.ID_Tarea, "", new { @class = "text-danger" })


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <br />

                        @Html.LabelFor(model => model.Remitente, "Remitente", htmlAttributes: new { @class = "control-label col-md-2" })

                        <input type="text" name="name" disabled value="@Session["Nombre"]" />
                        @Html.ValidationMessageFor(model => model.Remitente, "", new { @class = "text-danger" })



                        @{


                            if (Session["Rol"].Equals("Jefe"))
                            {
                                @Html.LabelFor(model => model.Destinatario1, "Destinatario 1", htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.DropDownList("Destinatario1", null, htmlAttributes: new { @class = "dropdown-trigger btn" })
                                @Html.ValidationMessageFor(model => model.Destinatario1, "", new { @class = "text-danger" })

                                @Html.LabelFor(model => model.Destinatario2, "Destinatario 2", htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.DropDownList("Destinatario2", null, htmlAttributes: new { @class = "dropdown-trigger btn" })
                                @Html.ValidationMessageFor(model => model.Destinatario2, "", new { @class = "text-danger" })

                                @Html.LabelFor(model => model.Destinatario3, "Destinatario 3", htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.DropDownList("Destinatario3", null, htmlAttributes: new { @class = "dropdown-trigger btn" })
                                @Html.ValidationMessageFor(model => model.Destinatario3, "", new { @class = "text-danger" })

                            }
                            else
                            {
                                @Html.LabelFor(model => model.JefeDestinatario, "JefeDestinatario", htmlAttributes: new { @class = "control-label col-md-2" })
                                <input type="text" name="JefeDestinatario" hidden disabled value="@Session["CedulaJefe"]" />
                                <input type="text" name="name" disabled value="@Session["Jefe_Inmediato"]" />

                                @Html.ValidationMessageFor(model => model.JefeDestinatario, "", new { @class = "text-danger" })

                            }
                        }

                        <br />

                        @Html.LabelFor(model => model.CantidadDeHoras, "Cantidad de horas", htmlAttributes: new { @class = "control-label col-md-2" })


                        @Html.EditorFor(model => model.CantidadDeHoras, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CantidadDeHoras, "", new { @class = "text-danger" })




                    </div>
                </div>



            </div>
            <div id="pagina">
                <input type="submit" value="Agregar" class="waves-button-input btn-small " />


                @*  @Html.ActionLink("Agregar", "NuevaSHE", null, htmlAttributes: new { @class = "waves-button-input btn-small " })*@


                @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small " })

            </div>
        </div>

    </div>


}

Views/Cuentas/Delete.cshtml
@model SistemaHE.Models.Cuentas

@{
    ViewBag.Title = "Delete";
}

<div id="textoH">
    <br />
    <h2>Cuentas</h2>
</div>

<div>
    <div id="ContentL">
        <div class="ContenidoL">
            <h3>¿Está seguro que desea eliminar esto?</h3>
            <div class="row">
                <div id="formula" class="col s6">


                    @Html.LabelFor(model => model.Contrasenna, "Contraseña", htmlAttributes: new { @class = "central-align", @style = "" })



                    @Html.EditorFor(model => model.Contrasenna, new { htmlAttributes = new { @class = "black-text", disabled = "disabled" } })

                    @Html.LabelFor(model => model.Usuarios.Nombre_Completo, "Nombre Completo", htmlAttributes: new { @class = "central-align" })


                    @Html.EditorFor(model => model.Usuarios.Nombre_Completo, new { htmlAttributes = new { @class = "black-text",  disabled = "disabled" } })
                </div>
            </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div id="pagina">

                    <input type="submit" value="Eliminar" class="waves-button-input btn-small  " />
                    @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small  " })

                </div>
            }


        </div>
    </div>
</div>

Views/Cuentas/Details.cshtml
@model SistemaHE.Models.Cuentas

@{
    ViewBag.Title = "Details";
}

<div id="textoH">
    <br />
    <h2>Cuentas</h2>
</div>

<div>

    <div id="ContentL">
        <div class="ContenidoL">
            <h3>Detalles</h3>

            <div class="row">


                <div id="formula" class="col l6">
                    @Html.LabelFor(model => model.Usuarios.Nombre_Completo, "Nombre Completo")
                    @Html.EditorFor(model => model.Usuarios.Nombre_Completo, new { htmlAttributes = new { @class = "", disabled = "disabled" } })

                    @Html.LabelFor(model => model.Identificacion, "Contraseña")
                    @Html.EditorFor(model => model.Contrasenna, new { htmlAttributes = new { @class = "", disabled = "disabled" } })

                </div>


            </div>

            <div id="pagina">
                @Html.ActionLink("Editar", "Edit", new { id = Model.ID_Cuenta }, htmlAttributes: new { @class = "waves-button-input btn-small " })
                @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small " })
            </div>

        </div>
    </div>

</div>

Views/Cuentas/Edit.cshtml
@model SistemaHE.Models.Cuentas

@{
    ViewBag.Title = "Edit";
}

<div id="textoH">
    <br />
    <h2>Cuentas</h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="ContentL">

        <div class="ContenidoL">

            <h3>Nueva Contraseña</h3>
            <div id="formula">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID_Cuenta)

                <div class="row">
                    <div class="col l6">
                        @Html.LabelFor(model => model.Identificacion, "Identificación")

                        @Html.EditorFor(model => model.Identificacion, new { htmlAttributes = new { @class = "", disabled = "disabled" } })


                    </div>

                    <div class="col l6">

                        @Html.LabelFor(model => model.Contrasenna, "Contraseña")


                        @Html.EditorFor(model => model.Contrasenna, new { htmlAttributes = new { @class = "", name= "Contrasenna" } })

                        @Html.ValidationMessageFor(model => model.Contrasenna, "Campo Obligatorio", new { @class = "text-danger" })


                    </div>

                </div>

            </div>
            <div id="pagina">

                <input type="submit" value="Guardar" class="waves-button-input btn-small" />


                @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "waves-button-input btn-small" })

            </div>
        </div>
    </div>




}

Views/Cuentas/Index.cshtml
@model IEnumerable<SistemaHE.Models.Cuentas>

@{
    ViewBag.Title = "Administracion de Cuentas";
}
<div id="textoH">
    <br />
    <h2>Cuenta</h2>
</div>



<div id="ContentL">

    <div class="ContenidoL">
        <table class="table">
            <tr>
           
                <th>
                    Nombre Completo
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
          
                    <td>
                        @Html.DisplayFor(modelItem => item.Usuarios.Nombre_Completo)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Cuentas", new { id = item.ID_Cuenta })">Nueva Contraseña
                            

                        </a>
                        @*<a href="@Url.Action("Details", "Cuentas", new { id = item.ID_Cuenta })">
                            <i class="material-icons">search</i>

                        </a>*@
                        @*<a href="@Url.Action("Delete", "Cuentas", new { id = item.ID_Cuenta })">
                            <i class="material-icons">delete</i>

                        </a>*@

                    </td>
                </tr>
            }

        </table>

    </div>
</div>